<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IotGatewayLearning.Application\IotGatewayLearning.Application.csproj" />
    <ProjectReference Include="..\IotGatewayLearning.Common\IotGatewayLearning.Common.csproj" />
    <ProjectReference Include="..\IotGatewayLearning.Infrastructure\IotGatewayLearning.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
